// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/qb/torrents/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qb/torrents/delete.post').default>>>>
    }
    '/api/qb/torrents/files': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qb/torrents/files.get').default>>>>
    }
    '/api/qb/torrents/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qb/torrents/info.get').default>>>>
    }
    '/api/qb/torrents/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qb/torrents/stats.get').default>>>>
    }
    '/api/qb/torrents/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qb/torrents/sync.post').default>>>>
    }
    '/api/torrents/bd-info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/torrents/bd-info.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/torrents/bd-info.post').default>>>>
    }
    '/api/torrents/files': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/torrents/files.get').default>>>>
    }
    '/api/volumes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/volumes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/volumes/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}